config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 5, maximum: 100}
    validates :description, presence: true, length: {minimum: 30, maximum: 400}  
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article 
    belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username,  presence: true,
                             uniqueness: { case_sensitive: false },
                              length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: {maximum: 105},
                        format: {with: VALID_EMAIL_REGEX}
                        has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    helper_method :current_user, :logged_in?, :require_user
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "You must be logged in to do this action"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :same_user, only: [:edit, :update, :destroy]

    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        @article.save
        flash[:notice] = "Article was create successfully"
        redirect_to @article
    end

    def edit
    end

    def update
        @article.update(article_params)
        flash[:notice] = "Article was update successfully"
        redirect_to @article
    end

    def destroy
        @article.destroy
        redirect_to @article
    end


    private

    def find_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [] )
    end

    def same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "you can only modified your own article"
            redirect_to @article
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, only: [:edit, :create]

    def new   
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category has been created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category has been edited"
            redirect_to category_path
        else
            render 'edit'
        end
    end

    def show
        @category = Category.find(params[:id])
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
       if !(logged_in? && current_user.admin?) 
        flash[:alert] = "Only admins can perform that action" 
       end
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      
    end

    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfuly"
        redirect_to user
      else
        flash[:alert] = "something wrong"
        redirect_to root_path
      end
    end

    def destroy 
      session[:user_id] = nil
      flash[:notice] = "Logged out"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_params, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the alpha blog #{@user.username} "
            redirect_to @user
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to @user
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account delete"
        redirect_to root_path
    end

    private 

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def find_params 
        @user = User.find(params[:id])
    end

    def same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "you can only modified your account"
            redirect_to user_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 150 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">

    <div class="row justify-content-center text-light">
        <div class="col-10">
            <%= form_with(model: @article, class: "bg-primary p-5 rounded", local: true) do |f| %>
                <div class="from-group row">
                    <%= f.label :title, class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control", placeholder: "Title of article"%>
                    </div>
                </div>

                <div class="from-group row pt-3 ">
                    <%= f.label :description, class: "col-2 col-form-label"%>
                    <div class="col-10">
                    <%= f.text_area :description, rows: 10,  class: "form-control", placeholder: "Description of article" %>
                    </div>
                </div>

                <div class="from-group row pt-3 ">
                    <%= f.label :category, class: "col-2 col-form-label"%>
                    <div class="col-10">
                    <%= f.collection_select(:category_ids, Category.all, :id, :name, 
                    {prompt: "Choose from the list below (optional)"}, { :multiple => true, class: "custom-select"} )%>
                    </div>
                </div>

                <div class="from-group row mt-3 justify-content-center">
                    <%= f.submit class: "col-3 btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
        </div>

        <div class="text-primary text-center mt-3"><%= link_to "Return to article listing", articles_path %></div>
    </div>

</div>

app/views/articles/_listing.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-8">
                <div class="card mt-4">
                    <div class="card-header bg-primary d-flex justify-content-between"> 
                        <div class="h5">
                            <% if article.user %> 
                                by <%= link_to article.user.username, user_path(article.user), class: "text-light" %>
                            <% end %>
                        </div>
                        <div class="text-muted">
                            <small> Created <%= time_ago_in_words(article.created_at)%> ago ,
                            updated <%= time_ago_in_words(article.updated_at)%> ago
                            </small>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                        <%= link_to "Show", article_path(article), class: "btn btn-outline-primary" %>
                        <% if logged_in? && (article.user == current_user || current_user.admin? ) %>
                        <%= link_to "edit", edit_article_path(article), class: "btn btn-outline-success" %>
                        <%= link_to "Delete", article_path(article), data: {"turbo-method": :delete}, class: "btn btn-outline-danger" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

    <!--<div class="text-center">
        <%= link_to "Create new article", new_article_path, class: "btn btn-outline-primary btn-lg m-4" %>
    </div>-->
</div>

app/views/articles/edit.html.erb
<h1 class="text-center text-primary m-3">Edit article</h1>

<%= render 'form' %>

<div class="text-center mt-2"><%= link_to "Delete article", article_path, data: {"turbo-method": :delete} %></div>

app/views/articles/index.html.erb
<h1 class="text-center m-4">Article listing page</h1>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

    <%= render 'listing' %>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center text-primary m-3 mb-3">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center primary m-4"><%= @article.title %></h1>

<div class="container">
        <div class="card text-center ">
            <div class="card-header bg-primary h4">
                by <%= @article.user.username if @article.user%>
                <div><%= link_to gravatar_for(@article.user, size: 70), user_path(@article.user) %></div>
                <% if @article.categories.any? %>
                    <% @article.categories.each do |category| %>
                        <div class="badge rounded bg-light text-primary mt-3 mb-3">
                            <%= link_to category.name, category_path(category) %>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                    <% if logged_in? && (@article.user == current_user || current_user.admin? ) %>
                        <%= link_to "edit", edit_article_path(@article), class: "btn btn-outline-success" %>
                        <%= link_to "Delete", article_path(@article), data: {"turbo-method": :delete}, class: "btn btn-outline-danger"  %>
                    <% end%>
                </div>
            <div class="card-footer text-body-secondary bg-primary text-muted">
               <small> Created <%= time_ago_in_words(@article.created_at)%> ago ,
                updated <%= time_ago_in_words(@article.updated_at)%> ago</small>
            </div>
        </div>
        <div class="text-primary text-center mt-3"><%= link_to "Return to article listing", articles_path %></div>
</div>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center text-light">
        <div class="col-10">
            <%= form_with(model: @category, class: "bg-primary p-5 rounded", local: true) do |f| %>
                <div class="from-group row">
                    <%= f.label :name, class: "col-sm-1 col-md-1 col-lg-1 col-form-label" %>
                    <div class="col-sm-11 col-md-11 col-lg-11">
                        <%= f.text_field :name, class: "form-control", placeholder: "Enter a name"%>
                    </div>
                </div>

                <div class="from-group row mt-3 justify-content-center">
                    <%= f.submit "Create a category", class: "col-sm-12 col-md-12 col-lg-3 btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
        </div>

        <div class="text-primary text-center mt-3"><%= link_to "Return to article listing", articles_path %></div>
    </div>

</div>

app/views/categories/edit.html.erb
<h1 class="text-center text-primary m-3 mb-3">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center text-primary m-3 mb-3">Categories listing</h1>

<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-8">
                <div class="card mt-4">
                    <div class="card-header bg-primary d-flex justify-content-between"> 
                        <div class="h4 text-center"><%= link_to category.name, category, class: "text-light" %></div>
                        <div class="text-muted">
                            <small> Created <%= time_ago_in_words(category.created_at)%> ago </small>
                        </div>
                    </div>
                    <div class="card-body text-center">
                        <%= link_to "Show category", category_path(category), class: "btn btn-outline-primary" %>
                        <% if logged_in? && current_user.admin?  %>
                            <%= link_to "Edit category", edit_category_path(category), class: "btn btn-outline-success" %>
                            <%= link_to "Delete category", category_path(category), class: "btn btn-outline-danger", data: {"turbo-method": :delete} %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <!-- <div class="text-center"> -->
        <!-- <%= link_to "Create new user", new_article_path, class: "btn btn-outline-primary btn-lg m-4" %> -->
    <!-- </div> -->
</div>

<div class="apple_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center text-primary m-3 mb-3">Create a category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center primary m-4"><%= @category.name %></h1>

app/views/layouts/_flash.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismis="alert" aria-label="close"></button>
        </div>
    <% end %>
</div>

<!--<div class="alert alert-success alert-dismissible fade show" role="alert"></div>
<button type="button" class="close" data-dismis="alert" aria-label="close">
    <span aria-hidden="true" >&times;</span>
</button>
</div>!-->

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-primary">
    <div class="container">
        <span class="text-light text-center">This is the footer of my blog</span>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-primary " >
    <div class="container-fluid ">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu bg-primary">
              <%= link_to "Articles listing", articles_path, class: "dropdown-item" %>
              <% if logged_in? %>
              <%= link_to "create article", new_article_path, class: "dropdown-item" %>
              <%= link_to 'Category', categories_path, class: "dropdown-item" %>
              <% end %>
            </ul>
          </li>
        </ul>

          <ul class="navbar-nav d-flex justify-content-end">
            <% if logged_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= "(Admin)" if current_user.admin? %> Profile <%= current_user.username %>
              </a>
              <ul class="dropdown-menu bg-primary">
                <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "Delete profile", user_path(current_user), data: {"turbo-method": :delete, confirm: "are you sure"}, class: "dropdown-item text-danger" %>
              </ul>
            </li>

              <li class="nav-item">
                <%= link_to 'Log out', logout_path, data: {"turbo-method": :delete}, class: "nav-link" %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'sign up', signup_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
       <!-- <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>-->
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>

  <body class="d-flex flex-column h-100" >


    
    <%= render 'layouts/navigation' %> 
    <%= render 'layouts/flash' %> 
    
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is the about page</h1>

<%= link_to "Articles listing", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="container" >
    <div class="m-3 p-5 rounded-3 d-flex align-items-center justify-content-center" id="bg-img">
        <div class="bg-primary p-5 rounded-5" >
            <h1 class="text-white">Welcome to my blog</h1>
            <%= link_to "sign up", signup_path, class: "btn btn-light btn-lg mt-3 text-primary " %>
        </div>
    </div>

</div>

app/views/users/_form.html.erb
<div class="container">

    <div class="row justify-content-center text-light">
        <div class="col-10">
            <%= form_with(model: @user, class: "bg-primary p-5 rounded", local: true) do |f| %>
                <div class="from-group row">
                    <%= f.label :username, class: "col-sm-2 col-md-2 col-lg-2 col-form-label" %>
                    <div class="col-sm-10 col-md-10 col-lg-10">
                        <%= f.text_field :username, class: "form-control", placeholder: "Enter a username"%>
                    </div>
                </div>

                <div class="from-group row pt-3 pb-3 ">
                    <%= f.label :email, class: "col-sm-2 col-md-2 col-lg-2 col-form-label"%>
                    <div class="col-sm-10 col-md-10 col-lg-10">
                        <%= f.email_field :email,  class: "form-control", placeholder: "Enter your email" %>
                    </div>
                </div>

                <div class="from-group row">
                    <%= f.label :password, class: "col-sm-2 col-md-2 col-lg-2 col-form-label" %>
                    <div class="col-sm-10 col-md-10 col-lg-10">
                        <%= f.password_field :password, class: "form-control", placeholder: "Enter a password"%>
                    </div>
                </div>

                <div class="from-group row mt-3 justify-content-center">
                    <%= f.submit(@user.new_record? ? "sign up" : "Update account", class: "col-sm-12 col-md-12 col-lg-3 btn btn-outline-light btn-lg") %>
                </div>
            <% end %>
        </div>

        <div class="text-primary text-center mt-3"><%= link_to "Return to article listing", articles_path %></div>
    </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center text-primary m-3 mb-3">Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center text-primary m-3 mb-3">Users listing</h1>

<div class="apple_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-8">
                <div class="card mt-4">
                    <div class="card-header bg-primary d-flex justify-content-between"> 
                        <div class="h5">by <%= link_to user.username, user, class: "text-light" %></div>
                        <div class="text-muted">
                            <small> Created <%= time_ago_in_words(user.created_at)%> ago </small>
                        </div>
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title"><%= link_to gravatar_for(user), user_path(user) %></h5>
                        <p class="card-text"><%= pluralize(user.articles.count, 'Articles') %></p>
                        <%= link_to "Show profile", user_path(user), class: "btn btn-outline-primary" %>
                        <% if logged_in? %> 
                            <% if user == current_user %>
                                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-success" %>
                            <% end %>
                            <% if current_user.admin? %>
                            <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", data: {"turbo-method": :delete} %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="text-center">
        <%= link_to "Create new user", new_article_path, class: "btn btn-outline-primary btn-lg m-4" %>
    </div>
</div>

<div class="apple_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center text-primary m-3 mb-3">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center text-primary m-3 mb-3"><%= @user.username %>'s profile</h1>

<div class=""><%= gravatar_for @user, size: 150 %></div>

<% if logged_in? && @user == current_user %>
    <div class="text-center">
        <%= link_to "Edit profile", edit_user_path, class: "btn btn-outline-primary btn-lg m-4" %>
    </div>
<% end %>

<h1 class="text-center text-primary m-3 mb-3">Articles</h1>

<%= render 'articles/listing' %>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>